### ISSUE TITLE
Leaving the project

### ISSUE THREAD

**Issue by mcornick** [hashivim/hashivim.github.io#1]
I'm no longer using any of the Hashicorp tools on a regular basis, and don't have time for or interest in keeping these projects up to date. Therefore, I am stepping out of the way and leaving the project in the hands of @mattyjones and @pgporada. Thanks, Matt and Phil, for responding to my call for maintainers.

As no one else was interested in the Homebrew tap, I've marked it as unmaintained. However, it remains fully operational and would just take someone running the autotap script to pick up new releases. (If someone was really clever, they could write a cron job to do it, maybe?)

Thanks to everyone who contributed and showed interest. As is the spirit of open source, I pass the torch to the new maintainers with my best wishes.

**Comment by pgporada** [comment]
Thanks for the projects Mark. You've been much appreciated here. Best of
luck to you.

**Comment by mattyjones** [comment]
I don't use homebrew often enough but I did pull this in debian. I could look at the homebrew stuff if it ever breaks.  Thanks for all the hard work!
