### ISSUE TITLE
New Hashivim logo

### ISSUE THREAD

**Issue by pgporada** [hashivim/hashivim.github.io#2]
Hey @mattyjones,

Let me know what you think about this potential logo. it's not much, but hopefully it's better than the github default. [potential logo](https://philporada.com/hashivim.png)

It's the Hashicorp logo with Vim in the middle.

**Comment by pgporada** [comment]
Ping

**Comment by mattyjones** [comment]
Sorry about that, I must of missed this. I am good with the logo. Great job!

**Comment by pgporada** [comment]
:+1: Appreciated dude

Just curious, are you on IRC at all? If so, I am SneakyPhil on Freenode. I'd love to talk one of these days.
